# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


# 启用 TPM 插件管理器 prefix+I
set -g @plugin 'tmux-plugins/tpm'

# # 示例插件（必装，增强 tmux 功能）
set -g @plugin 'tmux-plugins/tmux-sensible'

# 其他插件可以在这里继续添加
# set -g @plugin '用户名/仓库名'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


# 用下面的快捷键来管理和使用 resurrect 了：
# 保存会话：在当前 tmux 会话中，按下 prefix (Ctrl+b) 紧接着按下 Ctrl+s，状态栏会短暂提示“Saving...”，保存即完成。
# 恢复会话：重新打开终端后，启动一个 tmux 会话，然后按下 prefix (Ctrl+b) 紧接着按下 Ctrl+r，即可恢复到最近一次保存的状态。
# 💡 状态文件默认保存在 ~/.local/share/tmux/resurrect/ 目录。

# === continuum 配置选项 ===
# 设置自动保存间隔 (秒)，默认15分钟
set -g @continuum-save-interval '59' 
# 打开 tmux 时自动恢复上一次保存的会话
set -g @continuum-restore 'on' 
# 系统启动时自动启动 tmux (依赖于操作系统的自启功能)
set -g @continuum-boot 'on'
## (可选) 保存窗格的内容，如vim的文本，会占用更多空间
#set -g @resurrect-capture-pane-contents 'on'

# 1. 终端类型（必须 tmux-256color，不要 screen）
set -g default-terminal "tmux-256color"

# 2. 转发真彩色给内部程序（nvim 靠这个）
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",tmux-256color:RGB"

# 3. WSL2 额外兼容（undercurl/下划线颜色）
if-shell 'test -n "$WSL_DISTRO_NAME"' {
  set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
  set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
}

# 4. 启用 256 色
set-option -ga terminal-overrides ',*256col*:Tc'



set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"










# TPM 自动初始化脚本（必须放在最后一行）
run '~/.tmux/plugins/tpm/tpm'

